FROM ghcr.io/graalvm/native-image-community:21 AS builder

WORKDIR /app

RUN microdnf install findutils

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

COPY src ./src

RUN ./mvnw -Pnative native:compile -DskipTests

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/target/nempo-track-api /app/app

EXPOSE 8080

ENTRYPOINT ["/app/app"]